#!/bin/bash

# Blank line for clean output
echo

# Metadata
HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATETIME=$(date)

# OS Info
source /etc/os-release
OS="$NAME $VERSION"

# Uptime
UPTIME=$(uptime -p)

# CPU Info
CPU=$(lshw -class processor 2>/dev/null | grep "product" | head -1 | awk -F: '{print $2}' | sed 's/^ *//')

# RAM Info
RAM=$(free -h | awk '/^Mem:/ {print $2}')

# Disk Info
DISKS=$(lshw -class disk 2>/dev/null | grep -E 'product|size' | paste - - | awk -F: '{print $2 $4}' | sed 's/^ *//')

# Video Info
VIDEO=$(lshw -class display 2>/dev/null | grep "product" | awk -F: '{print $2}' | sed 's/^ *//')

# Host Address (default route interface)
DEF_IFACE=$(ip route | grep default | awk '{print $5}')
HOST_IP=$(ip -o -4 addr show $DEF_IFACE | awk '{print $4}' | cut -d/ -f1)

# Gateway
GATEWAY=$(ip route | grep default | awk '{print $3}')

# DNS Server
DNS=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | paste -sd "," -)

# Users Logged In
USERS=$(who | awk '{print $1}' | sort -u | paste -sd "," -)

# Disk Space
DISKSPACE=$(df -h --output=target,avail | grep -v "Mounted" | awk '{print $1 ": " $2}' | paste -sd ", " -)

# Process Count
PROCCOUNT=$(ps aux | wc -l)

# Load Average
LOADAVG=$(uptime | awk -F'load average: ' '{print $2}')

# Listening Ports
PORTS=$(ss -tuln | grep LISTEN | awk '{print $5}' | awk -F: '{print $NF}' | sort -un | paste -sd "," -)

# UFW Status
UFWSTATUS=$(sudo ufw status | head -n 1)

# Final Report Output
cat <<EOF

System Report for $HOSTNAME generated by $USERNAME, on $DATETIME

System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO
Host Address: $HOST_IP
Gateway IP: $GATEWAY
DNS Server: $DNS

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISKSPACE
Process Count: $PROCCOUNT
Load Averages: $LOADAVG
Listening Network Ports: $PORTS
UFW Status: $UFWSTATUS

EOF
